data:
  config: # details of the data (TODO: should this differ for each dataset?)
    root_folder: spkanon_eval
    # the following depend on the anonymization model
    sample_rate: ${sample_rate} 
    batch_size: ${batch_size}
    max_ratio: ${max_ratio}

  datasets:
    eval:
      #- spkanon_eval/data/mini_librispeech/ls-dev-clean-2.txt #old one for dev
      - spkanon_eval/data/librispeech/ls-test-clean.txt
    train_eval:
      - spkanon_eval/data/librispeech/ls-train-clean-360.txt
